service: restaurant-menu-optimizer
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    LLM_PROVIDER: ${env:LLM_PROVIDER, 'anthropic'}
    LLM_MODEL: ${env:LLM_MODEL, 'claude-3-opus-20240229'}
    USER_POOL_ID: ${self:custom.userPoolId}
    CLIENT_ID: ${self:custom.clientId}
    MENU_FILES_BUCKET: ${self:custom.menuFilesBucket}
  apiGateway:
    shouldStartNameWithService: true
    apiKeys: []
    binaryMediaTypes:
      - 'multipart/form-data'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-s3-local

custom:
  userPoolId: ${param:userPoolId, env:USER_POOL_ID, 'dev-user-pool'}
  clientId: ${param:clientId, env:CLIENT_ID, 'local-client-id'}
  menuFilesBucket: ${param:menuFilesBucket, env:MENU_FILES_BUCKET, 'local-menu-files-bucket'}
  dotenv:
    basePath: ${self:custom.basePath, './'}
    logging: true
    include:
      - LLM_PROVIDER
      - LLM_MODEL
      - LLM_API_KEY
      - CLIENT_ID
      - USER_POOL_ID
      - MENU_FILES_BUCKET
  webpack:
    webpackConfig: ./config/webpack.config.js
    includeModules: true
    packager: 'npm'
  serverless-offline:
    httpPort: 3000
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    installPath: ./dynamodb_local
    noStart: false
    install: false
    tables:
      - TableName: ${self:provider.stage}-restaurants
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: restaurantId
            AttributeType: S
        KeySchema:
          - AttributeName: restaurantId
            KeyType: HASH
      - TableName: ${self:provider.stage}-menu-items
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: restaurantId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: restaurantId-index
            KeySchema:
              - AttributeName: restaurantId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
      - TableName: restaurant-menu-files-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: fileId
            KeyType: HASH
  s3:
    port: 4569
    directory: /tmp
    buckets:
      - name: ${self:custom.menuFilesBucket}

functions:
  PreSignUp:
    handler: src/auth/triggers/pre-signup.handler
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: PreSignUp
    environment:
      USER_POOL_ID: ${self:provider.environment.USER_POOL_ID}
      CLIENT_ID: ${self:provider.environment.CLIENT_ID}

  PostConfirmation:
    handler: src/auth/triggers/post-confirmation.handler
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: PostConfirmation
    environment:
      USER_POOL_ID: ${self:provider.environment.USER_POOL_ID}
      CLIENT_ID: ${self:provider.environment.CLIENT_ID}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: "*"  # Use '*' for local, override with real ARN in AWS

  RegisterRestaurant:
    handler: src/auth/handlers/register-restaurant.handler
    events:
      - http:
          path: auth/register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  required:
                    - email
                    - password
                    - name
                    - restaurantName
                    - cuisineType
                    - location
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      minLength: 8
                    name:
                      type: string
                    restaurantName:
                      type: string
                    cuisineType:
                      type: string
                    location:
                      type: string
    environment:
      USER_POOL_ID: ${self:provider.environment.USER_POOL_ID}
      CLIENT_ID: ${self:provider.environment.CLIENT_ID}
      STAGE: ${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:SignUp
          - cognito-idp:AdminConfirmSignUp
          - cognito-idp:InitiateAuth
          - cognito-idp:GetUser
        Resource: "*"
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: "*"

  Login:
    handler: src/auth/handlers/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  required:
                    - email
                    - password
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
    environment:
      USER_POOL_ID: ${self:provider.environment.USER_POOL_ID}
      CLIENT_ID: ${self:provider.environment.CLIENT_ID}
      STAGE: ${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:InitiateAuth
          - cognito-idp:GetUser
        Resource: "*"
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: "*"

  ConfirmRegistration:
    handler: src/auth/handlers/confirm-registration.handler
    events:
      - http:
          path: auth/confirm-registration
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  required:
                    - email
                    - confirmationCode
                  properties:
                    email:
                      type: string
                      format: email
                    confirmationCode:
                      type: string
    environment:
      USER_POOL_ID: ${self:provider.environment.USER_POOL_ID}
      CLIENT_ID: ${self:provider.environment.CLIENT_ID}
      STAGE: ${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ConfirmSignUp
        Resource: "*"

  UploadMenu:
    handler: src/menu/handlers/upload-menu.handler
    events:
      - http:
          path: menu/upload
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  required:
                    - restaurantId
                    - fileName
                    - fileType
                    - fileSize
                  properties:
                    restaurantId:
                      type: string
                    fileName:
                      type: string
                    fileType:
                      type: string
                    fileSize:
                      type: number
          authorizer: aws_iam
    environment:
      MENU_FILES_BUCKET: ${self:provider.environment.MENU_FILES_BUCKET}
      STAGE: ${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: "*"
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:Query
        Resource: "*"

  ParseMenu:
    handler: src/menu/handlers/parse-menu.handler
    events:
      - http:
          path: menu/parse
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  required:
                    - restaurantId
                    - fileKey
                    - fileType
                  properties:
                    restaurantId:
                      type: string
                    fileKey:
                      type: string
                    fileType:
                      type: string
                    fileId:
                      type: string
          authorizer: aws_iam
    environment:
      MENU_FILES_BUCKET: ${self:provider.environment.MENU_FILES_BUCKET}
      STAGE: ${self:provider.stage}
      LLM_PROVIDER: ${self:provider.environment.LLM_PROVIDER}
      LLM_MODEL: ${self:provider.environment.LLM_MODEL}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: "*"
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:Query
          - dynamodb:BatchWriteItem
        Resource: "*"
      - Effect: Allow
        Action:
          - textract:DetectDocumentText
          - textract:StartDocumentTextDetection
          - textract:GetDocumentTextDetection
        Resource: "*"
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource: "*"

  EnhanceMenuDescriptions:
    handler: src/menu/handlers/enhance-menu-descriptions.handler
    events:
      - http:
          path: menu/enhance-descriptions
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  properties:
                    itemId:
                      type: string
                    restaurantId:
                      type: string
                    category:
                      type: string
                    targetAudience:
                      type: string
                    enhancementStyle:
                      type: string
                    batchSize:
                      type: number
                    llmProvider:
                      type: string
                  oneOf:
                    - required: ["itemId"]
                    - required: ["restaurantId"]
          authorizer: aws_iam
    environment:
      STAGE: ${self:provider.stage}
      LLM_PROVIDER: ${self:provider.environment.LLM_PROVIDER}
      LLM_MODEL: ${self:provider.environment.LLM_MODEL}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:Query
        Resource: "*"
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource: "*"

resources:
  Resources:
    userpool:
      Type: AWS::Cognito::UserPool
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        Schema:
          - Name: restaurantName
            AttributeDataType: String
            Mutable: true
          - Name: cuisineType
            AttributeDataType: String
            Mutable: true
          - Name: location
            AttributeDataType: String
            Mutable: true
    userpoolclient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: userpool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_CUSTOM_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
    restaurantstable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-restaurants
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: restaurantId
            AttributeType: S
        KeySchema:
          - AttributeName: restaurantId
            KeyType: HASH
    menufilesbucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: restaurant-menu-files-${self:provider.stage}
    menufilestable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurant-menu-files-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: fileId
            KeyType: HASH
    menuitemstable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-menu-items
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: restaurantId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: restaurantId-index
            KeySchema:
              - AttributeName: restaurantId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
  Outputs:
    UserPoolId:
      Value:
        Ref: userpool
      Description: "ID of the Cognito User Pool"
    UserPoolClientId:
      Value:
        Ref: userpoolclient
      Description: "ID of the Cognito User Pool Client"
    MenuFilesBucketName:
      Value:
        Ref: menufilesbucket
      Description: "Name of the S3 bucket for menu files"