name: Deploy Restaurant Menu Optimizer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "20"
  #         cache: "npm"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run tests
  #       run: npm test

  deploy:
    name: Deploy
    # needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            stage: dev
          - branch: develop
            stage: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS
        # if: github.ref == format('refs/heads/{0}', matrix.branch)
        if: false
        run: |
          # Check if stack exists to determine if this is first deploy
          if aws cloudformation describe-stacks --stack-name restaurant-menu-optimizer-${{ matrix.stage }} --region us-east-1 2>/dev/null; then
            echo "Stack exists, deploying with CloudFormation references..."
            serverless deploy --stage ${{ matrix.stage }} \
              --param="userPoolId=cf:restaurant-menu-optimizer-${{ matrix.stage }}.UserPoolId" \
              --param="clientId=cf:restaurant-menu-optimizer-${{ matrix.stage }}.UserPoolClientId" \
              --param="menuFilesBucket=cf:restaurant-menu-optimizer-${{ matrix.stage }}.MenuFilesBucketName" \
              --verbose
          else
            echo "First deploy, using default values..."
            serverless deploy --stage ${{ matrix.stage }} --verbose
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-frontend:
    name: Deploy Frontend
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./frontend

      - name: Build web
        run: flutter build web
        working-directory: ./frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync build/web s3://restaurant-menu-optimizer-frontend-dev/ --delete
        working-directory: ./frontend
